In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

## The Basics of the Pandas Library

In machine learning, very often we find ouselves working with tabular data, i.e. data sets that are organized in rows and columns. Every row of such a table reperesents a new observation, or instance, and every column contains feature or label values for all instances. In NumPy, we use integer numbers to index rows and columns. Pandas library makes it possible to use arbitray labels for indexing. 

Typically, we work either with Pandas series, which are one-dimnensional arrays of data, or with Pandas dataframes which may contain multiple columns. 

### Pandas Series

Let's take a look at Pandas series first.

In [ ]:
import pandas as pd

# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html
ps=pd.Series(data=[1, 2, 3, 4, 5], index=['one', 'two', 'three', 'four', 'five'])
print(ps)

one      1
two      2
three    3
four     4
five     5
dtype: int64

In [ ]:
# Data type
type(ps)

pandas.core.series.Series

In [ ]:
# Indexing
ps['three']

3

In [ ]:
# Slicing (note that the final index is included now!)
ps['two':'four']

two      2
three    3
four     4
dtype: int64

We will talk more about indexing and slicing of Pandas series.

In [ ]:
# Selecting only the values
ps.values

array([1, 2, 3, 4, 5])

In [ ]:
# The values are stored as a simple 1D NumPy array:
type(ps.values)

numpy.ndarray

In [ ]:
# Selecting only the index
ps.index

Index(['one', 'two', 'three', 'four', 'five'], dtype='object')

In [ ]:
# Creating a Pandas series object from a dictionary
population_2019 = pd.Series(data={'Pella': 10_231, 'Oskaloosa': 11_511, 'Des Moines': 215_636})
population_2019

Pella          10231
Oskaloosa      11511
Des Moines    215636
dtype: int64

### The basics of Pandas DataFrames

A Pandas DataFrame object can contain multiple columns. Fundamentally, each column is nothing but a Pandas series object. Let's create another series listing the areas of Pella, Oskaloosa, and Des Moines (in square miles).

In [ ]:
area_2019 = pd.Series(data={'Pella': 8.99, 'Oskaloosa': 8.039, 'Des Moines': 90.66})
print(area_2019)

Pella          8.990
Oskaloosa      8.039
Des Moines    90.660
dtype: float64

In [ ]:
# Build a DataFrame object
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html
data_2019 = pd.DataFrame({'population': population_2019, 'area': area_2019})

data_2019

            population    area
Pella            10231   8.990
Oskaloosa        11511   8.039
Des Moines      215636  90.660

In [ ]:
data_2019.index

Index(['Pella', 'Oskaloosa', 'Des Moines'], dtype='object')

In [ ]:
data_2019.columns

Index(['population', 'area'], dtype='object')

In [ ]:
# The index object can be easily converted to a Python list
idx=data_2019.columns.to_list()
idx

['population', 'area']

In [ ]:
# Constructing a data frame from a 2-dimensional NumPy array
import numpy as np

np.random.seed(42)
rand_array=np.random.randint(0, 10, size=(10, 5))

rand_df=pd.DataFrame(data=rand_array, index=[ch for ch in 'ABCDEFGHIJ'], columns=[ch for ch in 'ABCDE'])
rand_df

   A  B  C  D  E
A  6  3  7  4  6
B  9  2  6  7  4
C  3  7  7  2  5
D  4  1  7  5  1
E  4  0  9  5  8
F  0  9  2  6  3
G  8  2  4  2  6
H  4  8  6  1  3
I  8  1  9  8  9
J  4  1  3  6  7

In [ ]:
rand_df.shape

(10, 5)

In [ ]:
# Show only a specified number of rows (the default value is 6)
rand_df.head(4)

   A  B  C  D  E
A  6  3  7  4  6
B  9  2  6  7  4
C  3  7  7  2  5
D  4  1  7  5  1

### Indexing and slicing 

#### Pandas series

In [ ]:
ps1 = pd.Series(data=['A', 'C', 'D'], index=[1, 3, 5])
ps1

1    A
3    C
5    D
dtype: object

The index of a Pandas series that is specified explicitly is called the *explicit* index. In the example about the explicit indices are `[1, 3, 5]`. The existence of the explicit index is optional. In the absence of an explicitly defined index, Pandas is simply using integer row numbers for indexing (starting with zero), similar to NumPy arrays. This kind of index is called the *implicit* index and it is always available for both series and data frames. In our example the implicit indices are `[0, 1, 2]`. The difference between these two types of indices is often a great source of confusion. 

Conventionally, when for indexing operations with integer indices, explicit indices are implied.

In [ ]:
ps1[1]

'A'

In [ ]:
ps1[3]

'C'

In [ ]:
ps1[5]

'D'

However, for slicing operations, implicit indices are implied:

In [ ]:
ps1[1:3]

3    C
5    D
dtype: object

This convention might be very confusing, so Pandas provides a way to explicity specify what kind of indexing you want by using `loc` and `iloc` attributes for explicit and implicit indices, respectively. Here is how it works:

In [ ]:
# explicit indexing, yields the same result as ps1[1] above
ps1.loc[1]

'A'

In [ ]:
# implicit indexing, NumPy array style indexing
ps1.iloc[1]

'C'

In [ ]:
# explicit slicing (the last index is inclusive!)
ps1.loc[1:3]

1    A
3    C
dtype: object

In [ ]:
# implicit slicing, yields the same result as ps1[1:3] above
ps1.iloc[1:3]

3    C
5    D
dtype: object

It is a good idea to always use `loc` and `iloc` to make it clear what type of indexing you imply. This makes your code more readable and helps to avoid potential errors. 

The textbook also mentions the `ix` attribute. It is depreciated and we won't use it in our class.

#### Pandas data frames 

Let's make some data to work with. Here are some made up data showing the number of students and faculty memebers in different departments of some college XYZ:

In [ ]:
# Building a data frame from a dictionary of columns data 
depts=pd.DataFrame({'students': [23, 45, 67, 125, 11], 'faculty': [2, 4, 5, 7, 2]}, index=['HIST', 'ENG', 'BIO', 'CS', 'PHYS'])
depts

      students  faculty
HIST        23        2
ENG         45        4
BIO         67        5
CS         125        7
PHYS        11        2

In [ ]:
# Select a colums: dictionary-style

depts['faculty']

HIST    2
ENG     4
BIO     5
CS      7
PHYS    2
Name: faculty, dtype: int64

In [ ]:
# Alternatively, we can do it attribute style:
# (not always possible if there are conflicting names)

depts.faculty

HIST    2
ENG     4
BIO     5
CS      7
PHYS    2
Name: faculty, dtype: int64

In [ ]:
print(type(depts))
print(type(depts['faculty']))
print(type(depts.faculty))
print(type(depts.faculty.values))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'numpy.ndarray'>

In [ ]:
# Defining a new column is easy (avoid using attribute-style column assignment):

depts['classrooms'] = [5, 10, 8, 13, 6]

depts

      students  faculty  classrooms
HIST        23        2           5
ENG         45        4          10
BIO         67        5           8
CS         125        7          13
PHYS        11        2           6

In [ ]:
# You can use NumPy array-style indexing (integer position based style) using iloc attribute:
depts.iloc[1:4, :-1]

     students  faculty
ENG        45        4
BIO        67        5
CS        125        7

In [ ]:
# Or, you can use row and column names (label based style) with the loc attribute:
depts.loc['ENG':'CS', :'faculty']

     students  faculty
ENG        45        4
BIO        67        5
CS        125        7

In [ ]:
# One can use lists for row/column names:

majors = ['ENG', 'PHYS', 'HIST']
cols = ['classrooms', 'students']
depts.loc[majors, cols]

      classrooms  students
ENG           10        45
PHYS           6        11
HIST           5        23

In [ ]:
# If you want to keep all columns:

depts.loc[majors, :]

      students  faculty  classrooms
ENG         45        4          10
PHYS        11        2           6
HIST        23        2           5

In [ ]:
# If you want to keep all rows:

depts.loc[:, cols]

      classrooms  students
HIST           5        23
ENG           10        45
BIO            8        67
CS            13       125
PHYS           6        11

In [ ]:
# Boolean masks in the form of a Python list or a NumPy array with Boolean entries
# can also be used to make selection from a Pandas series/data frame:

# Create a new Boolean mask with True entries for departements with more than 30 students:

mask_1 = depts['students'].values > 30
depts[mask_1]

     students  faculty  classrooms
ENG        45        4          10
BIO        67        5           8
CS        125        7          13

In [ ]:
# Select departements with the number of faculty larger than 3 
# and more than 10 classrooms

mask_2 = (depts['faculty'].values > 3) & (depts['classrooms'].values > 10)
depts[mask_2]

    students  faculty  classrooms
CS       125        7          13

In [ ]:
# Apply 'mask_1' and select only the last two columns ('faculty' and 'classrooms')
# using explicit indexing:

depts.loc[mask_1, ['faculty', 'classrooms']]

     faculty  classrooms
ENG        4          10
BIO        5           8
CS         7          13

In [ ]:
# using implicit indexing:

depts.iloc[mask_1, -2:]

     faculty  classrooms
ENG        4          10
BIO        5           8
CS         7          13

### Loading data from a 'csv' file

Let's load our *Auto MPG* data set.

In [ ]:
from pathlib import Path

PATH = Path('/content/gdrive/My Drive/Colab Notebooks/Applied_Machine_Learning/Data/Auto_MPG')

# Loading data from a drive
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html
auto=pd.read_csv(PATH/'auto-mpg.csv')

# Another option is to download the data frame from a given url addresss
auto_web=pd.read_csv('https://raw.githubusercontent.com/graf10a/Applied-Machine-Learning-Course/main/Data/auto-mpg.csv')

In [ ]:
auto.head()

    MPG  Cylinders  Displacement  ...  Year  Origin                       Name
0  18.0          8         307.0  ...    70       1  chevrolet chevelle malibu
1  15.0          8         350.0  ...    70       1          buick skylark 320
2  18.0          8         318.0  ...    70       1         plymouth satellite
3  16.0          8         304.0  ...    70       1              amc rebel sst
4  17.0          8         302.0  ...    70       1                ford torino

[5 rows x 9 columns]

In [ ]:
auto_web.head()

    MPG  Cylinders  Displacement  ...  Year  Origin                       Name
0  18.0          8         307.0  ...    70       1  chevrolet chevelle malibu
1  15.0          8         350.0  ...    70       1          buick skylark 320
2  18.0          8         318.0  ...    70       1         plymouth satellite
3  16.0          8         304.0  ...    70       1              amc rebel sst
4  17.0          8         302.0  ...    70       1                ford torino

[5 rows x 9 columns]

In [ ]:
auto.shape

(398, 9)

In [ ]:
auto_web.shape

(398, 9)